// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/analytics/orphan-assignees": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "analytics"
                ],
                "summary": "Задачи, где assignee не член команды — валидация целостности (только admin)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_transport_http_analytics.orphanAssigneeResponse"
                            }
                        }
                    },
                    "403": {
                        "description": "не admin",
                        "schema": {
                            "$ref": "#/definitions/task_tracker_internal_transport_http_httpkit.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/analytics/teams": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "analytics"
                ],
                "summary": "Статистика команд: участники и done-задачи за 7 дней (только admin)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_transport_http_analytics.teamStatsResponse"
                            }
                        }
                    },
                    "403": {
                        "description": "не admin",
                        "schema": {
                            "$ref": "#/definitions/task_tracker_internal_transport_http_httpkit.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/analytics/top-creators": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "analytics"
                ],
                "summary": "Топ-3 создателей задач в каждой команде за месяц (только admin)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_transport_http_analytics.topCreatorResponse"
                            }
                        }
                    },
                    "403": {
                        "description": "не admin",
                        "schema": {
                            "$ref": "#/definitions/task_tracker_internal_transport_http_httpkit.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Аутентификация, выдаёт JWT",
                "parameters": [
                    {
                        "description": "email и пароль",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_transport_http_auth.loginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_transport_http_auth.loginResponse"
                        }
                    },
                    "400": {
                        "description": "невалидный json",
                        "schema": {
                            "$ref": "#/definitions/task_tracker_internal_transport_http_httpkit.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "неверные креды",
                        "schema": {
                            "$ref": "#/definitions/task_tracker_internal_transport_http_httpkit.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Текущий пользователь",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_transport_http_auth.userResponse"
                        }
                    },
                    "401": {
                        "description": "нет или невалидный токен",
                        "schema": {
                            "$ref": "#/definitions/task_tracker_internal_transport_http_httpkit.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/register": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Регистрация пользователя",
                "parameters": [
                    {
                        "description": "данные регистрации",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_transport_http_auth.registerRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal_transport_http_auth.userResponse"
                        }
                    },
                    "400": {
                        "description": "невалидные данные",
                        "schema": {
                            "$ref": "#/definitions/task_tracker_internal_transport_http_httpkit.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "email занят",
                        "schema": {
                            "$ref": "#/definitions/task_tracker_internal_transport_http_httpkit.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/tasks": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "Задачи команды с фильтрами и пагинацией",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id команды",
                        "name": "team_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "todo | in_progress | done",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "id исполнителя",
                        "name": "assignee_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "максимум записей (1..100, по умолчанию 20)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "последний увиденный id из next_cursor; без него — первая страница",
                        "name": "cursor",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_transport_http_tasks.taskListResponse"
                        }
                    },
                    "400": {
                        "description": "невалидные параметры",
                        "schema": {
                            "$ref": "#/definitions/task_tracker_internal_transport_http_httpkit.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "команда не найдена",
                        "schema": {
                            "$ref": "#/definitions/task_tracker_internal_transport_http_httpkit.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "Создать задачу (только член команды)",
                "parameters": [
                    {
                        "description": "задача",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_transport_http_tasks.createTaskRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal_transport_http_tasks.taskResponse"
                        }
                    },
                    "400": {
                        "description": "невалидные данные или assignee не член команды",
                        "schema": {
                            "$ref": "#/definitions/task_tracker_internal_transport_http_httpkit.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "команда не найдена",
                        "schema": {
                            "$ref": "#/definitions/task_tracker_internal_transport_http_httpkit.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/tasks/{id}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "Обновить задачу (член команды), изменения пишутся в историю",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id задачи",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "новое состояние",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_transport_http_tasks.updateTaskRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_transport_http_tasks.taskResponse"
                        }
                    },
                    "400": {
                        "description": "невалидные данные или assignee не член команды",
                        "schema": {
                            "$ref": "#/definitions/task_tracker_internal_transport_http_httpkit.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "нет прав",
                        "schema": {
                            "$ref": "#/definitions/task_tracker_internal_transport_http_httpkit.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "задача не найдена",
                        "schema": {
                            "$ref": "#/definitions/task_tracker_internal_transport_http_httpkit.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/tasks/{id}/history": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "История изменений задачи",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id задачи",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_transport_http_tasks.changeResponse"
                            }
                        }
                    },
                    "404": {
                        "description": "задача не найдена",
                        "schema": {
                            "$ref": "#/definitions/task_tracker_internal_transport_http_httpkit.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/teams": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "teams"
                ],
                "summary": "Команды, в которых состоит текущий пользователь",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_transport_http_teams.teamResponse"
                            }
                        }
                    },
                    "401": {
                        "description": "нет токена",
                        "schema": {
                            "$ref": "#/definitions/task_tracker_internal_transport_http_httpkit.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "teams"
                ],
                "summary": "Создать команду, создатель становится owner",
                "parameters": [
                    {
                        "description": "название",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_transport_http_teams.createTeamRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal_transport_http_teams.teamResponse"
                        }
                    },
                    "400": {
                        "description": "невалидные данные",
                        "schema": {
                            "$ref": "#/definitions/task_tracker_internal_transport_http_httpkit.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "нет токена",
                        "schema": {
                            "$ref": "#/definitions/task_tracker_internal_transport_http_httpkit.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/teams/{id}/invite": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "teams"
                ],
                "summary": "Пригласить пользователя в команду (owner/admin команды или глобальный admin)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id команды",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "email приглашаемого",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_transport_http_teams.inviteRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "невалидные данные",
                        "schema": {
                            "$ref": "#/definitions/task_tracker_internal_transport_http_httpkit.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "нет прав",
                        "schema": {
                            "$ref": "#/definitions/task_tracker_internal_transport_http_httpkit.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "команда или пользователь не найдены",
                        "schema": {
                            "$ref": "#/definitions/task_tracker_internal_transport_http_httpkit.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "уже в команде",
                        "schema": {
                            "$ref": "#/definitions/task_tracker_internal_transport_http_httpkit.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "internal_transport_http_analytics.orphanAssigneeResponse": {
            "type": "object",
            "properties": {
                "assignee_id": {
                    "type": "integer"
                },
                "task_id": {
                    "type": "integer"
                },
                "team_id": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "internal_transport_http_analytics.teamStatsResponse": {
            "type": "object",
            "properties": {
                "done_last_7d": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "members": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "internal_transport_http_analytics.topCreatorResponse": {
            "type": "object",
            "properties": {
                "rank": {
                    "type": "integer"
                },
                "tasks_created": {
                    "type": "integer"
                },
                "team_id": {
                    "type": "integer"
                },
                "team_name": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                },
                "user_name": {
                    "type": "string"
                }
            }
        },
        "internal_transport_http_auth.loginRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "internal_transport_http_auth.loginResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                }
            }
        },
        "internal_transport_http_auth.registerRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "internal_transport_http_auth.userResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                }
            }
        },
        "internal_transport_http_tasks.changeResponse": {
            "type": "object",
            "properties": {
                "change_group_id": {
                    "description": "ChangeGroupID один на все поля, изменённые одним запросом",
                    "type": "string"
                },
                "changed_at": {
                    "type": "string"
                },
                "changed_by": {
                    "type": "integer"
                },
                "field": {
                    "type": "string"
                },
                "new_value": {
                    "type": "string"
                },
                "old_value": {
                    "type": "string"
                }
            }
        },
        "internal_transport_http_tasks.createTaskRequest": {
            "type": "object",
            "properties": {
                "assignee_id": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "team_id": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "internal_transport_http_tasks.taskListResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_transport_http_tasks.taskResponse"
                    }
                },
                "next_cursor": {
                    "description": "NextCursor передаётся в следующий запрос параметром cursor;\nnull — страниц больше нет",
                    "type": "integer"
                }
            }
        },
        "internal_transport_http_tasks.taskResponse": {
            "type": "object",
            "properties": {
                "assignee_id": {
                    "type": "integer"
                },
                "completed_at": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "created_by": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "team_id": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "internal_transport_http_tasks.updateTaskRequest": {
            "type": "object",
            "properties": {
                "assignee_id": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "internal_transport_http_teams.createTeamRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "internal_transport_http_teams.inviteRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                }
            }
        },
        "internal_transport_http_teams.teamResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                }
            }
        },
        "task_tracker_internal_transport_http_httpkit.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "JWT в формате: Bearer {token}",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Task Tracker API",
	Description:      "Сервис управления задачами с командной работой и историей изменений.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
